Update requirements.txt with missing package
While trying to import the CNBC_Streaming getting an error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'parsel' is not defined
so adding the missing package